const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/3.jpg",
    band: "Nirvana",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  // Adicione mais produtos aqui com as respectivas categorias
  {
    title: "Álbum Forró",
    category: 3,
    price: 35.0,
    img: "./src/assets/img/5.jpg",
    band: "Artista do Forró",
    year: 2005,
    id: 4,
  },
  {
    title: "Samba Total",
    category: 4,
    price: 42.0,
    img: "./src/assets/img/6.jpg",
    band: "Grupo do Samba",
    year: 2010,
    id: 5,
  },
  {
    title: "Baião na Veia",
    category: 5,
    price: 28.0,
    img: "./src/assets/img/7.jpg",
    band: "Banda de Baião",
    year: 1998,
    id: 6,
  },
  {
    title: "Rap Nacional",
    category: 6,
    price: 30.0,
    img: "./src/assets/img/8.jpg",
    band: "Grupo de Rap",
    year: 2003,
    id: 7,
  },
  {
    title: "Hip-Hop Hits",
    category: 7,
    price: 35.0,
    img: "./src/assets/img/9.jpg",
    band: "Artista de Hip-Hop",
    year: 2015,
    id: 8,
  },
  {
    title: "Reggae Vibe",
    category: 9,
    price: 25.0,
    img: "./src/assets/img/10.jpg",
    band: "Banda de Reggae",
    year: 2008,
    id: 9,
  },
  {
    title: "Country Life",
    category: 10,
    price: 40.0,
    img: "./src/assets/img/11.jpg",
    band: "Country Star",
    year: 1995,
    id: 10,
  },
  {
    title: "Gospel Worship",
    category: 11,
    price: 32.0,
    img: "./src/assets/img/12.jpg",
    band: "Worship Band",
    year: 2020,
    id: 11,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
